<repositories>
    <repository>
        <id>panda-repository</id>
        <url>https://repo.panda-lang.org/releases</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>net.dzikoysk.funnyguilds</groupId>
        <artifactId>funnyguilds</artifactId>
        <version>4.14.0</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
